import type { Metadata } from 'next';
import cn from 'classnames';
import localFont from 'next/font/local';
import { Inter } from 'next/font/google';
import '@/app/styles/main.scss';

import Navbar from './components/layout/navigation/Navbar';
import Footer from './components/layout/footer/Footer';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});
const audrey = localFont({
  src: [
    {
      path: '../assets/fonts/Audrey/Audrey-Normal.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Audrey/Audrey-Normal.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Audrey/Audrey-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Audrey/Audrey-Medium.woff',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Audrey/Audrey-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Audrey/Audrey-Bold.woff',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-audrey',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(audrey.variable, inter.variable)}>
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
